# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /all/:categories/:year/:title/
relative_permalinks: true

# Site Setup
url:                 http://wommy.github.io/
baseurl:             jekyll-lanyon/
# paginate
# paginate:          5
# paginate_path:     /:num/

# Site Specifics
title:               Wommy
tagline:             Digital
descriptionOld:      'a Blog built for/by <a href="http://github.com/wommy" target="_blank">Wommy</a>, with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>, <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>, & <a href="http://prose.io" target="_blank">Prose</a>'
description:         'built by'

# About/Contact
author:
  name:              Tommy Williams
  nick:              Wommy
  url:               https://twitter.com/froggie92
  email:             tom@technomad.media

github:
  repo:              https://github.com/wommy/jekyll-lanyon/
  version:           1.0.0

#development
product:
  name:				 techNomad
  website:			 http://wommy.github.io/jekyll-lanyon/
dev:
  name:				 Wommy
  website:  		 http://wommy.github.io/jekyll-lanyon/

# prose
prose:
  siteurl:           'http://wommy.github.io/jekyll-lanyon/'
  ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
    - atom.xml
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
    pages:
      - name: "layout"
        field:
          value: "page"
      - name: "permalink"
        field:
          value: "/{{page.title}}/"
